void Ext_Printer_Stop(void);
void Send_Dairy_Name_ID(void);
void Write_USB_File(UINT8);
void Restart_DPU(void);
void Read_RTC(void);
void Shift_Right(BYTE * buf,UINT8 snok);
void Shift_Right1(BYTE *buf,UINT8 ,UINT8 );
void Settings_SubMenu_Header(UINT8 );
void Read_Settings_Menu_Fun_Cnt(void);
UINT8 User_Selected_Menu_List(UINT8 funtype);
void Disp_Msg_Big(UINT8 ,UINT8 );
void Write_Default_Dealer_Settings(void);
UINT8 Change_Shift_Search(void);

UINT8 Function_Selected(UINT8 maxfuns,UINT8 presentcount);
void Disp_Up_Down_Select(void);
UINT8 Select_Yes_No(UINT8 scnt,UINT8 stype);
void Admin_Permissions(void);

void Disp_Msg_Boarder(void);
void Shift_Left(BYTE * ,UINT8 );
UINT8 Member_Code_Entry(UINT8);
void Server_Menu_Header(UINT8);
void CLR_Enabled(char *tbuf);
void Display_Snf_Limits(void);
UINT32 Get_Member_Address(UINT16);
void Read_Member_CODE(UINT16 );
void Read_Current_Shift_Col_Record(UINT16 );
void Clear_Transaction_Counters(void);
void Buf_Type(UINT8,char *tbuf);
void Send_Collection_Ext_Display(void);
void Ext_Print_Header(void);
void Exit_Any_Key(UINT8);
void Init_Regular_Font(void);
void Send_Tare_Command(void);
void Display_Table_Names(UINT8);
void Please_Wait_Msg_Small(UINT8);
 void Write_Incentive_Data(void);
 void Init_Weighing_Machine(void);
 void Disable_UART_Interrupts_WM(void);
 void Clear_Samples_Data(void);
 void Back_SubMenu(void);
void Print_LS_Report(UINT8,UINT8);
UINT8 USB_Payment_Register_Start(void);
void USB_Payment_Register_Record(UINT16,UINT8);
void USB_Payment_Register_Total_Summary(void);
void Read_Member_Comm_Type(UINT16);
void Display_Col_Shift(UINT8);
void Print_Barcode(void);
void SMS_Summary_Report(void);
void Start_End_Hours(UINT8);
void Msg_Delivery_Ack(void);
void Server_Control_Settings(void);
void ProcessDeductions(void);
UINT8 Start_End_Date_Month(void);
void Read_Date_Month_Year(void);
void Display_Modem_STATUS(void);
void GPRS_Menu_Header(UINT8 hflag);
UINT8 Connect_WIFI_Modem(void);
void Check_New_RateChart(void);
void Send_SCT_Close(void);
void Disp_Header_Boarder(void);
void Saved_Message(void);
void Check_Wifi_Modem(void);
//UINT8 Init_Wifi_Modem(void);
void Init_Wifi_Modem(void);
UINT8 No_Response_Error(void);
UINT8 Check_Selected_WIFI_In_List(void);

UINT8 Wifi_List(void);
UINT8 Connect_GPRS(void);
UINT8 Transfer_Shift_Data(UINT8 ttype);
void Init_Cum_Values(void);
UINT8 Confirm_Yes(void);
void Update_FAT_FLASH(void);
void Erase_SNF_Table(UINT8);
void Dummy_Bills(void);
void Delete_All_Members(void);
UINT8 Up_Down(UINT8 ,UINT8 );

void Add_Dummy_Members(void);
void Member_Header(UINT8);
UINT8 Connect_GPRS(void);
UINT8 Receive_Rate_Charts(void);
void Server_Messages(void);
void Display_RTC(UINT8);
void Send_RTC(void);
void Display_Code_Name(UINT8 line);
void Edit_Sangh_Sale(UINT8);
void Read_BillDetails(UINT32);
void Read_Local_Sale(void);
void Read_Sangh_Sale(void);
void Import_Export_Header(UINT8);//
UINT8 Password_Entry(UINT8);
UINT8 Start_End_Members(UINT8);
UINT8 Read_Value(char *buf,FSFILE * file);
void Ext_Print_Monthly_Report_Start(void);
void Ext_Print_Daywise_Report_Record(UINT16,UINT8);
void Ext_Print_Daywise_Report_Start(void);

void Display_Shift(UINT8);
void Sangh_Sale_Report(UINT8);
void Member_Bill(UINT8);
void Absent_Members(UINT8);
void Payment_Register(UINT8);
void SetDate_Time(UINT8);
void Collection(void);
void Deduction(UINT8);
void Local_Sale(UINT8,UINT8);
void Sangh_Sale(UINT8);
void Check_Balance(void);
void Add_Member(void);
void Shift_Report(UINT8);
void View_Shift_Report(void);
void Detailed_Shift_Report(UINT8,UINT8);
void Summary_Shift_Report(UINT8);
void Member_Details(void);
void View_Summary_Report(UINT8,UINT8);
void InitRTC(void);//(UINT8);
void Write(BYTE);

void RTCStart(void);
void RTCStop(void);
void RTCWriteByte(BYTE ,BYTE );
BYTE RTCReadByte(BYTE );
BYTE Read(void);

UINT8 KEY_ASCII(UINT8,UINT8);
UINT8 KEY_ALPHA(UINT8);
void Buzzer(UINT8 );
void Hex_DEC(UINT8 ,INT32 ,BYTE * ,UINT8 );
void FLASHReadString(UINT32 ,UINT32 ,BYTE *);
void Write_Analyzer_Data(void);
void Display_Box(UINT8);
void Display_Boarder2(void);
void Please_Wait_Msg(UINT8);

void Send_SMS_MemberBill(void);
void WM_SendByte(BYTE);
void Write_Settings(void);

extern void USBOTGInitialize(void);
UINT8 ON_OFF(UINT8);
void Send_Payment_Register(void);
void Send_Detailed_Shift_Report(void);

void Paper_Feed(UINT8);
void GPRS_SendString(BYTE*);
void GPRS_RecString_SIM(BYTE*);
void Display_RTC_Big(void);
void Milk_Collection(UINT8);
void Mode_Selection(void);
void Collection_Settings(void);
void Ext_Print_Report_Date_Time(void);
void Ext_Print_Average_Total(UINT8);
void Ext_Printer_SendString(void);
void Ext_Printer_SendString_3636Bold(void);
void Ext_Printer_SendString_Bold(void);
void Ext40_Print_Heading(UINT8);
void Ext_Print_From_To_Date(void);
void EXT_PRINT_UNDERSCORE(UINT8);
void SEERAMReadString(UINT32,UINT16,char *);
void Get_MIN_MAX_Code(void);
void Payment_Summary_Report(UINT8);

void Ext_Paper_Feed(UINT8);
void Ext_Print_Date(UINT8);

UINT8 FatMin_Max(UINT8);
UINT8 SNFMin_Max(UINT8);

void Balance_Command(void);
void Modem_Restart(void);
void Display_Bill_Details(UINT8,UINT8);
void checking_modem(void);
void Server_Communication(UINT8);
UINT8 Close_Shift(UINT8 cstype);
void Hex_ASCII(UINT8 ,BYTE * );
UINT32 Float_Long(BYTE * );
void Milk_Collection_2Analyzers(UINT8 );
void Calculate_Rate(UINT8 usesnf_status);
void SEERAMWriteString(UINT32 ,UINT16,BYTE *);
void Print_Receipt(UINT8 );
void Ext_Print_Receipt(UINT8 );
void Read_Quantity(UINT32 );
void Read_Member_MilkType(UINT16 );
void Send_Collection_Ext_Display(void);
void Disable_Analyzer_Interrupts(void);

void Read_UltraPro_Inputs(BYTE * );
void Read_Ultra_Inputs(BYTE * );
void Calculate_Milko_Tester_Inputs(BYTE * );
void Calculate_Lacto_Inputs(BYTE * ,UINT8 );
void Calculate_Ksheera_Inputs(BYTE * );
void Read_Member_Name(UINT16 );
UINT8 HEX_ASCII(UINT8 );
void Send_SMS_BackEnd(UINT8,UINT16 );
UINT8 Connect_Server_Backend(void);
void Disconnect_Modem(void);
UINT16 Inc_Wt_AN_SMS_UL_Count(UINT8);
UINT8 SIM_Check(void);
void Display_SIM_STATUS(void);
UINT8 Init_GPRS_Modem(void);
void Read_Sample_No(void);
void Display_BackEnd_Msg(void);
void Read_Member_Details(UINT16);
void Add_Collection_Record(UINT8,BYTE * );
void TempUpdate_Upload_Flag(UINT16);
void Sector_Erase(UINT32 );
UINT16 Inc_Upload_Count(UINT8 );
void Set_Transaction_Counters(void);
void Read_Transaction_Counters(void);
void Calculate_Analyzer_Data(BYTE *);
UINT8 Wait_Backend_To_Complete(void);
void Display_Counters(void);
void Memberwise_Report(UINT8 ,UINT8 );
void Summary_Report(UINT8,UINT8,UINT8);
void SP_SendString(char *,UINT8);
void Reset_Tra_Counters(void);
void Read_CLR_Water(UINT16 );
void Display_Analyzer_Data(UINT8);
UINT16 Read_Member_SNO(UINT16);
UINT16 DynamicRead_BillDetails(UINT32 );
void Read_Collection_Flags(void);
void Ext_Printer_Bonus_Start(void);
void Ext_Print_Bonus_Record(UINT16 tempcode,UINT32 bonusamount,UINT8 milktype);
void Ext_Print_Bonus_Totals(UINT32 totalqty,UINT32 totalamt,UINT32 totalbonus);
UINT8 Ext_Print_Heading(UINT8);
void Ext40_Print_Member_Shift_Record(void);
void Ext40_Print_Payment_Register_Start(void);

void Ext80_Print_Member_Shift_Record(void);
UINT8 Insert_USB_To(void);
void Send_UNDERSCORE(UINT8);
UINT8 USB_Memberbill_Start(void);
void Send_Member_Bill_Report(UINT16);
void USB_Send_Memberbill_Shift_Record(void);
void EXT_Report_Header(UINT8 headlength);

void Ext_Print_Member_List_Start(UINT8);
void Ext_Print_Member_List_Record(UINT16);
void Ext_Print_Shift_Report_Start(void);
void Ext_Print_Shift_Report_Record(void);
void Ext_Print_Shift_Report_Total(void);

void Ext80_USB_Member_Shift_Record(UINT8 rectype);
void USB_Ext80_Payment_Register_Record(UINT8,UINT16,UINT8);

void USB_Ext80_Payment_Register_Total_Summary(UINT8);
UINT8 USB_Ext80_Payment_Register_Start(UINT8);

UINT32 Read_Incentive_Comm(UINT8,struct CollectionStructure);
void Temp_Data_Saving(UINT32 );
void Edit_Flash_Data(UINT32 ,UINT32,char *);
UINT16 Read_CurrentShiftDetails(UINT16 membercode);
void Print_Monthly_Report_Record(UINT16 pcode,UINT8 pmilk,UINT8 printertype);

