//LCD File Variables 
UINT8 DISPLAY_FIRST_LINE,DISPLAY_LAST_LINE,DISPLAY_NO_SPACES,NOR_DISPLAY_LAST_LINE;
UINT8 FONT_TYPE,DISPCHAR_TYPE,FIRST2,LAST2,BOARDER,CURSOR_BLINK,TEMP_CURSOR_BLINK,CURSOR_FLAG,DISP_CURSOR_FLAG;
UINT8 Dev_Addr,grphlcdX,grphlcdY,Display_Invert,INVERT_DISPLAY,CLEAR_BUF_FLAG;

BYTE DISPLAY_BUF[20],LBUF[30];

UINT8 MAIN_MENU_TOTAL_FUNS=0,SETTINGS_TOTAL_FUNS=0,MEMBER_TOTAL_FUNS=0;
//PS2 Keyboard Variables

UINT8 Shift_Lock,Caps_Lock,SCAN_REC_DATA,PRESSED_KEY,Key_Press,KBV;
UINT8 Ext_Code,Scan_Code,Prev_Data,Pres_Data,LED_Blink;
UINT8 Key_Int_Flag,Unmatch,K_Index_Cnt,Bit_Count;
UINT16 PREV_TOUCH_KEY_CODE;

//RTC Variables

BYTE Time[10];
UINT8 Temp_RTC1,Temp_RTC2,Big_RTC,Shift_Index;

//Printer Variables

BYTE PBUF[100];
BYTE CODE_BUF[16],MNO_BUF[16];
UINT8 Print_LineNo,Print_Feed_Status,Ext_Print_L,PRINTER_STATUS;

//USB Variables

UINT8 USB_FILE;
size_t numBytes;
BYTE myData[1024];
volatile BOOL deviceAttached;
FSFILE * myFile;
UINT8 FileCheck,USB_Check_Flag;

//FLASH Variables

UINT8 Flash_No;
UINT8 DEALER_SELECTION;

//GPRS Variables
UINT8 DPS_FLAG=0,DPS_FLAG2=0;
UINT8 SIM_INSERTED=0,SMS_Flag,ROAMING,CONNECT_FLAG;
UINT8 MODEM_ERROR,MODEM_STABLED=0,MODEM_COUNTER=0,SIM_PRESENT;
UINT8 SERVER_STATE,SMS_STATE,SIM_CHECK_STATE,INIT_MODEM_STATE,CHECK_SIM_FLAG,MSG_SENT_ACK;
UINT8 Modem_Init_Flag,Signal_Strength,MODEM_PRESENCE,MODEM_STATUS,SERVER_READ_STATUS;
UINT8 OK_ERROR,No_Response,GPRSDELAYCOUNT,Expected_Response;

BYTE Operator[20],GPRS_BUF[1500],GPRSOK_BUF[1500],SIM_NO[20];
BYTE SEND_BUF[1500],GPRSSEND_BUF[1500],REC_BUF[200],REC_BUF2[200];
//BYTE DPS_BUF[50];

UINT16 Max_Timer_Count,TimerCount;

//Global Variables

UINT8 *PTR_ADDR;

UINT8 Invert1,Invert2,Invert3;
UINT8 FN_KEY,MODE_FLAG;
UINT8 GET_VALUE_STATUS,LOGIN_TYPE,ZERO;
UINT8 NAME_SEARCH,SHIFT_SEARCH,TIME_RIGHT_ARROW;
UINT8 NUM_SIGN,MENU_ACCESS,TIME_FLAG,ANY_KEY,STANDBY;


BYTE Temp_Arr[21],Int_Arr[10];

BYTE SOCIETY_CODE[11],MACHINE_ID[7],SEARCH_BUF[21],BRAND_NAME[20];


UINT8 READ_FAT_VALUE1,READ_FAT_VALUE2;

//General Variables

UINT8 SERVER_C_TYPE,RTC_Response,RTC_Counter,SECONDS_COUNTER,NO_OF_FLASHES,MULTIPLE_SAMPLES,MILK_SELECTION;
UINT8 CURRENT_FLASH_NO,TEST_SHIFT_CNT,TOUCH_KEYPAD_DATA,PS2_KEYBOARD,MULTIPLE_SHIFTS,DISP_INTERVAL_CNT;

UINT32 RECORD_NO,CURRENT_SHIFT_NO;

UINT8 ONLYONESHIFT=0;

UINT8 CollectionFlag,BACKEND_FLAG,Analyzer_Header_Display_Flag,JUNK_DATA;
UINT8 Server_Rate_Chart_Flag=0,IncentiveReportFlag=0;
UINT8 I_Index_Count,I_Index_Count2,DATABYTE,DATABYTE2,GPRSDATABYTE,ANALYZER_FLAG,ANALYZER_FLAG2,GPRS_FLAG,Update_Analyzer_Flag,Update_Analyzer_Flag2,A_No_Bytes,A_No_Bytes2;
UINT8 WM_FLAG,WMCount,Wt_Sign,WM_Dot_Pos,WM_DATABYTE,BYTEGAPCOUNT,BYTEGAPCOUNT2;

UINT16 PENDING_SAMPLES_CNT,GPRS_BYTE_COUNT;

UINT8 LowFatFlag,HighFatFlag,Fat_Reject_Flag,Snf_Reject_Flag,Bonus_Type;
UINT16 Temp_SNF,Temp_FAT;
UINT8 EFFECT_RATE,SERVER_CONTROL;

UINT8 ON_LINE,ONLINE_BACKEND_FLAG;

UINT16 Round_Amt,Weight;
UINT16 Bonus_Rate;
UINT16 SF,EF,SS,ES;

UINT16 Member_SNo,Member_Code,NO_OF_CUSTOMERS,TEMPMEMBERSNO;
UINT16 MIN_CODE,MAX_CODE,DEVICE_CODE;

UINT32 TS_Rate,MILK_FAT,MILK_SNF,CUM_AMOUNT,TS_RATE_F,TS_RATE_S;
UINT32 Amount,sangh_amount;
UINT32 EEPROM_ADDR,TEMPEEPROM_ADR,AEEPROM_ADDR,MONTH_ADDR,DAY_ADDR,NO_OF_DAYS;
UINT32 User_Password,Entered_Pword;

UINT32 AVG_FAT_CALC,AVG_SNF_CALC,AVG_CLR_CALC,AVG_RATE_CALC;
UINT32 TOTAL_MEMBERS,TOTAL_PAID_AMT,TOTAL_QTY,TOTAL_INCENTIVE,TOTAL_AVG_RATE,TOTAL_AMT,TOTAL_QTY_COW,TOTAL_AMT_COW;
UINT32 B_MEMBERS,B_TOTAL_PAID_AMT,B_TOTAL_QTY,B_TOTAL_INCENTIVE,B_TOTAL_AVG_RATE,B_AVG_RATE_CALC,B_TOTAL_AMT,TOTAL_QTY_BUF,TOTAL_AMT_BUF;
UINT32 ALREADY_PAID_AMOUNT,ALREADY_PAID_QTY;
INT32 TOTAL_DEDUCTION,B_TOTAL_DEDUCTION;

BYTE DED_BUF[20],DOMAIN_SERVER_NAME[25];
BYTE BACKEND_RECORDS_BUF[1500],BACKEND_RECORD_COUNT;
BYTE Analyzer_Arr[21],WMBuf[50];

BYTE Flash_Buffer[15000],Flash_Buffer1[5000];
BYTE Global_Buffer[5000],TEMP_BUF[1000];//,ACK_BUF[100];

float TEMP_FLOAT_VALUE;
UINT16 RATE_BUF_INDEX,RATE_BUFFER[16500];


float FAT_MIN,FAT_MAX,SNF_MIN,SNF_MAX;

UINT8 SNF_CHART_TYPE;
UINT32 TEMP_LONG;

UINT8 SHIFT_READ_FLAG,MONTH_READ_FLAG,DATE_READ_FLAG;
UINT8 Fetch_Customer_Flag,TSDate,TEDate,TSMonth,TEMonth,TSYear,TEYear,TShift;
UINT16 S_SNo,E_SNo,Shiftrec_SNo;

UINT8 STD_SNF,LOW_SNF;
UINT16 DED_AMT,INC_AMT;
UINT16 SMS_DAY_LIMIT;

//UINT16 MESSAGE_STATUS1;
float VOLTAGE,MAX_INPUT_VOLTAGE;
UINT8 VOLTAGE_HIGH_ACCEPT=0,MONITOR_VOLTAGE=0,MACHINE_LOCK,DISABLE_VOL_BUZ;

UINT8 A1DELAYCOUNT,A2DELAYCOUNT;
UINT8 Only_Connect=0,TWO_ANALYZERS,TIMEWISE;
UINT8 WEIGHT_KG,WEIGHT_UNIT,WM_MIN_DIG;
UINT8 DEDUCTION_FLAG,CLR_BASED;
UINT8 LEFT_ARROW_EDIT;

UINT16 WEIGHT_COUNT,ANALYZER_COUNT,SMS_COUNT,UPLOAD_COUNT,PREV_U_COUNT,DU_COUNT;
UINT16 NO_COLLECTIONS,PRESENT_MEMBER_NO;
UINT16 TEMPFAT,TEMPSNF;



